{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf500
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red26\green26\blue26;\red249\green249\blue249;\red29\green111\blue63;
\red83\green83\blue83;}
{\*\expandedcolortbl;;\cssrgb\c13333\c13333\c13333;\cssrgb\c98039\c98039\c98039;\cssrgb\c12549\c50196\c31373;
\cssrgb\c40000\c40000\c40000;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl336\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
name: python \cf4 3.7\cf2 \
dependencies:\
  \cf5 -\cf2  python\cf5 =\cf4 3.7\cf2 \
  \cf5 \cb3 -\cf2 \cb3  xarray\
  \cf5 \cb3 -\cf2 \cb3  cartopy\
  \cf5 \cb3 -\cf2 \cb3  matplotlib\
  \cf5 \cb3 -\cf2 \cb3  cmocean\
\pard\pardeftab720\sl336\partightenfactor0
\cf2 \cb3   \cf5 -\cf2  seaborn}