{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf500
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red26\green26\blue26;\red249\green249\blue249;\red29\green111\blue63;
\red83\green83\blue83;\red26\green26\blue26;\red249\green249\blue249;}
{\*\expandedcolortbl;;\cssrgb\c13333\c13333\c13333;\cssrgb\c98039\c98039\c98039;\cssrgb\c12549\c50196\c31373;
\cssrgb\c40000\c40000\c40000;\cssrgb\c13333\c13333\c13333;\cssrgb\c98039\c98039\c98039;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl336\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 name: python \cf4 \strokec4 3.7\cf2 \strokec2 \
dependencies:\
  \cf5 \strokec5 -\cf2 \strokec2  python\cf5 \strokec5 =\cf4 \strokec4 3.7\cf2 \strokec2 \
  \cf5 \strokec5 -\cf2 \strokec2  numpy\
\pard\pardeftab720\sl336\partightenfactor0
\cf6 \cb7 \outl0\strokewidth0   \cf5 -\cf6  xarray\
  \cf5 -\cf6  cartopy\
\pard\pardeftab720\sl336\partightenfactor0
\cf6 \cb7   \cf5 -\cf6  matplotlib\
  \cf5 -\cf6  cmocean}